language: python
cache: pip
install: travis_retry pip install -U tox

stages:
  - validate
  - test
  - coverage
  - deploy


jobs:
  include:
    - stage: validate
      script: tox -e flake8
      python: 3.8
    - stage: validate
      script: tox -e bandit
      python: 3.8
    - stage: validate
      script: tox -e mypy
      python: 3.8
    - stage: test
      python: 3.6
      script: tox -e py36
    - stage: test
      python: 3.7.9
      script: tox -e py37
    - stage: test
      python: 3.8
      script: tox -e py38
    - stage: test
      python: 3.9
      script: tox -e py39
    - stage: coverage
      script:
        - pip install codecov==2.1.10
        - tox -e coverage
      python: 3.8
      include:
          if: branch = master
      after_success:
        - codecov
    - stage: deploy
      python: 3.8
      deploy:
        provider: pypi
        user: __token__
        password: $PYPI_TOKEN
