language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"

stages:
  - validate
  - test
  - name: coverage
    if: branch = main
  - name: deploy
    if: branch = main

install: pip install tox

jobs:
  include:
    - stage: validate
      script: tox -e flake8
      python: 3.8
    - stage: validate
      script: tox -e bandit
      python: 3.8
    - stage: validate
      script: tox -e mypy
      python: 3.8
    - stage: test
      script: tox
    - stage: coverage
      script:
        - pip install codecov==2.1.10
        - tox -e coverage
      python: 3.8
      after_success:
        - codecov
    - stage: deploy
      script: echo "Building to PyPI"
      deploy:
        provider: pypi
        user: __token__
        password: $PYPI_TOKEN
      python: 3.8
